# Procedures

We aim to enroll 100 health professional students at the University of Wisconsin (UW) over the course of 3 years (Each Summer; 2021-2023). Participants will be randomized to the BAM intervention (n = 50) or a control group (n = 50) that receives an educational pamphlet on ways to reduce anti-fat bias in clinical care. Participants in the BAM group will complete two peer-led, 2-hour sessions in which they will (1) Define anti-fat bias and fatphobia and explore how these constructs manifest in personal beliefs, interpersonal interactions, and in the healthcare setting, (2) Recognize and explore anti-fat bias in their personal and professional lives, (3) Learn new ways to challenge anti-fat bias in themselves, others, and future practice, and (4) Discuss ways to challenge anti-fat bias and weight stigma on an institutional and societal level with an emphasis on the healthcare system. While anti-fat bias is pervasive, we will specifically recruit medical students as they are early in clinical training, as existing biases may be less entrenched and more malleable in this population.


## Recruitment
Identified avenues for recruitment include: (1) posting on healthcare student listservs, (2) presenting the study at MD student interest groups, (3) student researchers involved with the project will provide study announcements in class listservs, (4) direct, peer-to-peer recruitment by MD and MD/MPH student researchers.


