# Intervention

## Weight-Bias Brochure

## The Body Advocacy Movement Intervention for Healthcare Professionals (BAM-Health)

The BAM-Health intervention leverages both cognitive dissonance and exposure-based intervention strategies, adapting common exercises used to promote body acceptance and challenge sociocultural body ideals to specifically target anti-fat bias and fatphobia among healthcare students. Dissonance-based prevention programs specifically aim to change internalized beliefs by asking participants to speak and act in ways that reject such beliefs. When individuals repeatedly speak and act in ways that contradict internalized beliefs, such beliefs are likely to shift to align with new patterns of behavior.16,18 In addition to dissonance, exposure is a relevant therapeutic mechanism specifically designed to challenge beliefs that are linked with feared outcomes.19,20 When engaging in exposure exercises, individuals act in ways that challenge fears in order to specifically test expectations regarding the likelihood of and/or their ability to emotionally manage feared outcomes, leading to reductions in both internalized fears and behavioral avoidance over time.19  S. 

### Session 1 
Session 1 includes introductions, discussing identities and clarifying terminology, and an exercise in defining anti-fat bias and fatphobia and ways in which these biases present in the healthcare setting, discussion of how weight and health intersect in both personal and professional settings, and identification of ways individuals can uproot internalized fatphobia and anti-fat bias (e.g. diversifying social media feed and reading lists). Participants will choose one way to do this in the coming week. Participants are also  asked to complete an imaginal exposure exercise at home where in which they will write and then recount several times during the week a ‘worst-case scenario’ of what they might fear could happen if they gained a significant amount of weight

### Session 2
Session 2 will include a debrief of the homework and a series of role plays. In these role plays, peer facilitators will play the role of a friend, colleague, or patient in a situation that evokes anti-fat attitudes, and participants will practice challenging anti-fat attitudes. Participants will also identify ways to uproot anti-fat bias in the healthcare system and commit to engaging in one activity to do so in the coming week. They will also be asked to write a ‘response letter’ to their worst-case scenario as an exit exercise 


## Peer Facilitators

We employ a peer-facilitated model of group intervention in this program, where a small group facilitators  undergo an 12-hour training program, similar to @sticeClinicianLedPeerLedInternetDelivered2017. Peer facilitators will train in teams – each peer-leader team will role-play delivery of the entire intervention and observed other peer leaders teams do the same, receiving live clinical supervision. 


## Intervention Fidelity
Sessions will be audio recorded and reviewed by two members of research staff. Audio recorded sessions will be rated for fidelity and competence. Research staff will independently code a randomly selected sample of 50% of sessions for implementation fidelity and facilitator competence using checklists assessing the major exercises and discussion topics for each session. Each component will be rated for degree of accurate presentation (10-point scale from “No adherence; the section was skipped” to “Perfect; all material in the section was presented as written”). Facilitator competence will be rated using 12 items assessing indicators of competence (e.g., leaders express ideas clearly and at an appropriate pace, leaders attempt to allot equal speaking time for all members) on a 10-point scale. 

