# Self-Report Measures

## Childhood Trauma Questionnaire
The Childhood Trauma Questionnaire (CTQ) is a standardized self-report inventory that measures the severity of childhood trauma and participants’ tendency to underreport maltreatment, and has been validated in both clinical and non-clinical populations [@bernsteinValidityChildhoodTrauma1997; @villanoPsychometricUtilityChildhood2004]. The CTQ is a retrospective 28-item self-report inventory that measures the severity of different types of childhood trauma, producing five clinical subscales each comprised of five items: Emotional Abuse, Physical Abuse, Sexual Abuse, Emotional Neglect, Physical Neglect. The measure also includes a three-item Minimization/Denial scale indicating the potential underreporting of maltreatment. Participants respond to each item in the context of “when you were growing up” and answer according to a five-point Likert scale ranging from “never” = 1 to “very often” = 5, producing scores of 5 to 25 for each trauma subscale. The three items comprising the Minimization/Denial scale are dichotomized (“never” = 0, all other responses = 1) and summed; a total of one (1) or greater suggests the possible underreporting of maltreatment (false negatives).

**Scoring**

Scoring for the CTQ includes: 

1. Renaming variables with descriptive names

2. Creating sum scores for each subscale (5 items for each of the 5 subscales)

3. Dichotomizing items for the minimization scale

4. Summing dichotimized items to create the minimization score

**Key Variables**

All variables below with appendix _25 reflect the final scoring of weighted subscale sum scores with < 25% missing data.

`ctq_emo_abuse_25` 

`ctq_phys_abuse_25`

`ctq_sex_abuse_25` 

`ctq_emo_neglect_25`

`ctq_phys_neglect_25`

`ctq_minimize_complete` (CTQ minimization score - completers only)

## Demographics
Demographics captured in the current study include: Race, Sexual Orientation, Gender, Ethnicity, Student Status, Working Status, Current Living Situation, Assessment Date, and Age

**Scoring**

Demographics are primarily drawn from the data collection form (measure prefix 'dcf'). Cleaning steps include:

1. Selection of variables that are part of the data collection form (prefix 'dcf') and winnow variables to be included in the master dataset. 

2. Calculation of age in years and remove birthdate (HIPPA Identifier) from the data set. 

3. Changing assessment date to only capture month and year of assessment for further de-identification.

4. Binning categorical variables to response options most appropriate for race and ethnicity

**Key Variables**

`age` (Participant Age in Years)

`race` (Participant Race, recoded to: White[0], Black[1], Asian[2], Mixed Race/Other[3])

`ethnicity` (Hispanic[1] or non-Hispanic[0]) 

`race_eth_1` (Race and ethnicity recoded to: White[0], Non-Hispanic Black [1], Non-Hispanic Asian [2], Hispanic [3], Mixed/Other [4])

`race_eth_2` (Race and ethnicity recoded to: White [0], Asian [1], Other [2])

`sex_orientation` (Participant sexual orientation, recoded to: Heterosexual [0], Bi/Pansexual [1], Gay/Lesbian [2])

`sex_minority` (Participant sexual orientation recoded to Hetersoxesual[0] or Sexual Minority[1])

`gender` (Participant gender identity recoded to Male[0], Female [1], NonBinary/Other[2])

`gender_TNB` (Participant gender identity recoded to: Cisgender [0] or Trans/Nonbinary [1])

`gender_female_nb` (Participant gender identity coded to Male = 0 and Female/Nonbinary = 1)

`sex_gender_minority` (Participant sexual and gender identity coded to CisHet [0] or Sexual/Gender Minority [1])

`assessment_month` (assessment recoded to assessment month and year)

## Dieting and Weight History Questionnaire (DWHQ)

The Dieting and Weight History Questionnaire (DWHQ), was developed by @wittAssessingThreeTypes2013 to measure three dimensions of dieting: (1) frequency of past dieting and overeating (i.e. history of dieting), (2) current dieting to lose weight, and (3) weight suppression, or the difference between an individual’s current weight and his or her highest previous weight.  

**Scoring**

**Key Variables**

## ED History Questionnaire (EDHQ)
The Eating Disorder History Questionnaire was developed by the EMBARK Lab for the current project to assess eating disorder history in the sample. It was used in baseline assessment for the current project prior to September, 2022, at which point the ED100k was substituted as it has been supported through initial validation for this purpose. The Eating Disorder History Questionnaire follows diagnostic algorithmic scoring to assess (via self-report) for history of eating disorder behaviors along with DSM-5 Anorexia Nervosa, Atypical Anorexia Nervosa, Bulimia Nervosa, Binge Eating Disorder, and Subclinical Eating Pathology. 

**Scoring**

**Key Variables**


## Fat Phobia Scale - Short Form 

The shortened Fat Phobia Scale (FPS)  utilizes 14 questions to assess fatphobia (from the 50-item original scale). It is intended to measure fat phobia levels in the tested population through various personality traits and whether there is bias when people apply them to an overweight person (@baconFatPhobiaScale2001). The shortened FPS questionnaire demonstrates high reliability when compared to the original 50 question scale. The FPS uses a 5-point sliding scale with 1 being equal to a different negative descriptive variable for each respective question and 5 being equal to a different positive variable for each respective question. Some items are reverse scored prior to data aggregation such that th 1 (negative) to 5 (positive) valuation is maintained across the scale.

**Scoring**

Data Cleaning includes: 

**1-2.** Selecting and renaming variables to include descriptive terms from questions in the scale.

**3.** Coding  all items such that the negative descriptor is labeled as 1 and the positive descriptor is labeled as 5.

**4.** Computing a mean score using all 14-items 

**Key Variables**

`fps_mean` (Mean score of all 14 items)


## Generalized Anxiety Disorder 7-item (GAD-7)

Generalized Anxiety Disorder 7-item (GAD-7) [@spitzerBriefMeasureAssessing2006] is a seven-item instrument that is used to measure or assess the severity of generalised anxiety disorder (GAD). Each item asks the individual to rate the severity of his or her symptoms over the past two weeks. Response options include “not at all”, “several days”, “more than half the days” and “nearly every day”. The GAD-7 is a widely-used and well-validated measure for anxiety screening [@sapraUsingGeneralizedAnxiety2020]. the GAD-7 is scored on a unidimensional scale summing all 7 items, with cutoffs that can also be employed for interpretation of clinical severity: 
|
|   Minimal anxiety = 0-4
|   Mild Anxiety = 5-9
|   Moderate Anxiety = 10-14
|   Severe Anxiety = 15-21. 
|
| A score of 10 points or higher indicates probably anxiety disorder, with 89% sensitivity and 82% specificity for GAD.

**Scoresheet**

Data Cleaning includes: 

**1-2** Selecting only the variables that are relevant for the current measure and recoding raw variables to make them consistent with the way of scoring: not at all = 0, several days =1, over half the days = 2, nearly every day =3

**3-5** creation an additional variable based on sum scores reflecting the participant's anxiety levels

**6** creating a dichotomized measure of likely anxiety (cutoff score of 10 or greater), along with clinical severity index (minimal, mild, moderate, severe)

**Key variables**

`gad_sum_25` (Sum of GAD-7, 25% or less items missing and weighted by N items completed)

`gad_cutoffs` (GAD-7 with anxiety severity cutoffs employed)

`gad_anx_disorder` (GAD-7 probable anxiety disorder Yes/No)


## Goldfarb Fear of Fat Scale

The Goldfarb Fear of Fat Scale (GFFS) is a 10-item scale which was introduced in 1985 as a diagnostic tool to measure one's fear of fat as it can be an indicator for the development of an eating disorder [@goldfarbGoldfarbFearFat1985]. When used as a screening tool for both clinical and non-clinical groups, GFFS has strong test-retest reliability and psychometric properties [@przybyta-basistaExaminationFactorStructure2022]. In addition, the test also has shown high validity for both populations with and without eating disorders (Goldfarb, 2010) While original factor structure is defined as a single-factor, @przybyta-basistaExaminationFactorStructure2022 also supported a two-factor structure in a non-clinical sample: (1) fear of weight gain and (2) fear of losing control over eating/weight. GFFS uses a 4-point scale with 1 being equal to very untrue and 4 being equal to very true

**Scoring**

Data Cleaning includes: 

**1-2.** Select and rename variables; recode labels scale to begin at 0 instead of 1 with very untrue being equal to 0 and very true being equal to 3. 

**3-4.** Sum the total scores and create a variable to reflect only those completing > 75% of items. Also create two subscales (FOWG and Fear of LOC) for alternative scoring. 

|**Scoring Note** Our GFFS scoring procedure re-scales the item scores to be 0-3 instead of 1-4, meaning that sum scores are scaled 0-21 instead of 7-28. To compare our means to other studies using the GFFS, add 7 to the sum score.

**Key Variables**

For variables below, _25 appendix reflects that individuals with <25% missing items on a scale were included with weighted sums based on number of items completed

`gffs_sum_25` (sum of all items)

`gffs_fowg_25` (sum of fear of weight gain subscale)

`gffs_loc_25` (sum of loss of control items)

## Ideal Body Stereotype Scale - Revised (IBSS-R)

The Ideal Body Stereotype Scale - Revised (IBSS-R), is a brief (6-item), unidimensional scale designed to measure internalization of an ideal-body stereotype (specifically for women), developed by @sticeTestDualPathway1996. The IBSS-R has be utilized as a measure of thin-ideal internalization in eating disorder prevention research [@sticeMetaanalyticReviewDissonancebased2019], making it suitable as a benchmark measure for existing effect sizes. 

**Scoring**

Scoring includes:

**1.** Selecting and renaming variables.

**2.** Creating a mean score from all 6 IBSS items

**Key Variables**

`ibss_mean_25` (Mean of all IBSS items, 25% or less missing)



## Sociocultural Attitudes Towards Appearance Questionnaire (SATAQ)

The Sociocultural Attitudes Towards Appearance Questionnaire-4 (SATAQ) is designed to assess societal and interpersonal aspects of appearance ideals. The SATAQ has five validated factors:  Internalization of Thin/Low Body Fat, Internalization of Muscular/Athletic, Pressures from Family, Pressures from Media, and Pressures from Peers. This scale structure was confirmed in 3 independent and geographically diverse samples of women from the United States (East Coast N = 440, West Coast N = 304, and North/Midwest N = 349). SATAQ-4 scale scores demonstrated excellent reliability and good convergent validity with measures of body image, eating disturbance, and self-esteem. The measure was also validated in college males from the United States (N = 271); however, there was some evidence of an underlying structure unique to men. For the purposes of the current data, the 5-factor structure is employed in scoring.

**Scoresheet**

Cleaning Steps include: 

**1-3.** Selecting raw variables being used and renaming variables to include numbering for order of questions in the scale; recoding labels scale to begin at 0

**4.** Generate total score and subscale scores: 

|   Internalization of thinness/low Body Fat: 
|   Internalization of muscular/athletic:
|   Pressures - family:
|   Pressures - peers:
|   Pressures - media:

**Key Variables**

Variables with the _25 appendix indicate that these variables include those with 25% or less missing data

`sataq_mean_25`	(mean of SATAQ)

`sataq_thin_ideal_25`	(mean of internalization of the thin ideal)

`sataq_athletic_ideal_25`	(mean of internalization of athletic ideal)

`sataq_parental_pressure_25`	(mean of parental pressure)

`sataq_peer_pressure_25`	(mean of peer pressure)

`sataq_media_pressure_25`	(mean of media pressure)


## Universal Measure of Bias - Fat (UMB-fat)

This companion file is for the Universal Measure of Bias - Fat (UMB-Fat) which was introduced in 2008 to assess weight bias and demonstrates strong psychometric properties when utilized as an assessment [@dursoUnderstandingSelfdirectedStigma2008]. It has been compared alongside two other scales measuring universal bias against 'gay' or 'Muslim' individuals and demonstrates high internal consistency and construct validity [@latnerWeighingObesityStigma2008]. Further, higher BMI is not associated with any differences in weight bias. The UMB-Fat uses a 7-point likert scale with 1 being equal to strongly agree and 7 being equal to strongly disagree. In terms of scoring, sums of scores are separated amongst four categories of bias: adverse judgement, social distance, attraction, and equal rights. 

**Scoring**

Data cleaning includes:

**1.** Selecting and renaming variables to include descriptors of questions asked in the scale 

**2.** Reverse coding questions 5, 7, 8, 9, 12, 15, 16, and 19 so that higher scores indicate greater stigma

**3.** Creation of subscale scores: 

- Sum the total scores of questions 5, 7, 12 ,15 , 16  = `umb_adverse_judgement_sum`

- Sum the total scores of questions 2, 8, 17, 19, 20  = `umb_social_distance_sum`

- Sum the total scores of questions 3, 4, 6, 9, 10 = `umb_attraction_sum`

- Sum the total scores of questions 1, 11, 13, 14, 18 = `umb_equal_rights_sum`

- Sum the total score with sum of all items as `umb_sum_total`


**Key Variables**

 All variables below reflect the final scoring of subscale sum scores with < 25% missing data (weighted sums used for those with any missing data).
 
`umb_adverse_judgement_sum_25` (adverse judgement against fat people)

`umb_social_distance_sum_25` (bias in the form of social distance from fat people)

`umb_attraction_sum_25` (bias in the form of attraction towards fat people)

`umb_equal_rights_sum_25` (bias in the form of opinons of equal rights for fat people)

`umb_sum_total_25` (sum of total umb-FAT scores - 25% or less missing)

